# Generated by Django 4.0.5 on 2022-06-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='flag',
            field=models.CharField(default='images/...png', max_length=20),
            preserve_default=False,
        ),
    ]
