# Generated by Django 4.0.5 on 2022-06-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='pwd',
            field=models.CharField(max_length=200),
        ),
    ]
