# Generated by Django 4.0.5 on 2022-07-06 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0008_test_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='role',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='tickets',
            old_name='flight_id',
            new_name='flight',
        ),
        migrations.RemoveField(
            model_name='airlines',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='user_id',
        ),
        migrations.AddField(
            model_name='airlines',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='flag',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.DeleteModel(
            name='Admins',
        ),
        migrations.DeleteModel(
            name='UserRoles',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
