# Generated by Django 4.0.5 on 2022-07-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_remove_users_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_from', models.CharField(max_length=20)),
                ('_about', models.TextField(default='')),
                ('_content', models.TextField(default='')),
                ('_received', models.DateTimeField(auto_now=True)),
                ('_reply_sent', models.DateTimeField()),
            ],
        ),
    ]
