# Generated by Django 4.0.5 on 2022-08-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0010_customerservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('_user_id', models.IntegerField()),
                ('_first_name', models.CharField(max_length=20)),
                ('_last_name', models.CharField(max_length=20)),
                ('_email', models.CharField(max_length=50)),
                ('_permission_requested', models.IntegerField()),
                ('_permission_denied', models.IntegerField()),
            ],
        ),
    ]
